apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "8"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"maplebank-api","namespace":"default"},"spec":{"replicas":3,"selector":{"matchLabels":{"app":"maplebank-api"}},"template":{"metadata":{"labels":{"app":"maplebank-api"}},"spec":{"containers":[{"image":"maplebank-api:v1","imagePullPolicy":"IfNotPresent","livenessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":10,"periodSeconds":10},"name":"maplebank-api","ports":[{"containerPort":5000}],"readinessProbe":{"failureThreshold":3,"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":5,"periodSeconds":5},"startupProbe":{"failureThreshold":12,"httpGet":{"path":"/health","port":5000},"initialDelaySeconds":5,"periodSeconds":5}}]}}}}
  creationTimestamp: "2026-09-16T14:27:42Z"
  generation: 8
  labels:
    app: maplebank-api
  name: maplebank-api
  namespace: default
  resourceVersion: "43329"
  uid: 8bd33b4b-520d-47eb-95e9-736024c169d5
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: maplebank-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: maplebank-api
    spec:
      containers:
      - image: maplebank-api:v1
        imagePullPolicy: IfNotPresent
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 10
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: maplebank-api
        ports:
        - containerPort: 5000
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        resources: {}
        startupProbe:
          failureThreshold: 12
          httpGet:
            path: /health
            port: 5000
            scheme: HTTP
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1
          timeoutSeconds: 1
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 3
  conditions:
  - lastTransitionTime: "2026-09-18T15:23:25Z"
    lastUpdateTime: "2026-09-18T15:23:25Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2026-09-16T14:27:42Z"
    lastUpdateTime: "2026-09-18T16:39:52Z"
    message: ReplicaSet "maplebank-api-665748b89d" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 8
  readyReplicas: 3
  replicas: 3
  terminatingReplicas: 0
  updatedReplicas: 3
