apiVersion: v1
kind: ServiceAccount
metadata:
  name: maplebank-api-sa
  namespace: maplebank-dev
  annotations:
    azure.workload.identity/client-id: "fbceaec0-3809-4f97-bbd7-3ef1be4b8e58"
  labels:
    azure.workload.identity/use: "true"